version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.1

jobs:

  Deploy:
    parameters:
      env:
        type: string
    machine:
      image: ubuntu-2004:current
    resource_class: arm.large
    steps:
      - checkout
      - aws-cli/setup:
          profile_name: default
      - run:
          name: Setup Custom Environment Vars
          command: |
            echo 'export ENVIRONMENT="<< parameters.env >>"' >> "$BASH_ENV"
      - run:
          name: Deploy OpenSearch
          command: |
            sh ./scripts/deploy-open-search.sh
      - run:
          name: Update the Database Schema and Generate an Index Template for OpenSearch
          command: |
            sh ./scripts/run-migrations.sh
      - run:
          name: Deploy Traefik
          command: |
            sh ./scripts/deploy-traefik.sh
      - run:
          name: Deploy Report Portal Services
          command: |
            sh ./scripts/deploy-report-portal-services.sh

workflows:

  DEPLOY_STAGE:
    jobs:
      - Deploy:
          name: Deploy Report Portal to Stage
          env: stage
          context:
            - PLAYON_SHARED_STAGE_AWS

