version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.1

jobs:

  Deploy:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.large
    steps:
      - checkout
      - aws-cli/setup:
          profile_name: default
      - run: aws ecs list-services --cluster playon-shared-qe-services-staging

# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  STAGE-BUILD:
    jobs:
      - Deploy:
          name: Deploy Report Portal
          context:
            - PLAYON_SHARED_STAGE_AWS



# VS Code Extension Version: 1.5.1
